[package]
name = "segtree-malloc"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["dylib"]

[dependencies]
rustix = { version = "0.38", features = ["stdio"], default-features = false }
segtree-alloc.path = ".."
